import type { Metadata } from "next";
import "./globals.css";
import Footer from "./sections/Footer";
import { QuantityProvider } from "../app/context/QuantityContext";
import { CartProvider } from "./context/CardContext";

export const metadata: Metadata = {
  title: "UI-UX-Hackathone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <CartProvider>
      <QuantityProvider>
        {children}
      </QuantityProvider>
    </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
