import type { Metadata } from "next";
import "./globals.css";
import Footer from "./sections/Footer";
import { QuantityProvider } from "../app/context/QuantityContext";
import { CartProvider } from "./context/CardContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


export const metadata: Metadata = {
  title: "Funiture website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
        <ToastContainer />
          <QuantityProvider>{children}</QuantityProvider>
        </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
